### ISSUE TITLE
Add pre-commit hooks 

### ISSUE THREAD

**Issue by RusseII** [sparksuite/salary-calculator#70]
I noticed you are [manually running](https://github.com/sparksuite/salary-calculator/commit/c49454dbd50ab36198338ff38e8d445b623a14a9) the `yarn format` command.

You should add a pre-commit tool like [lint-staged](https://github.com/okonet/lint-staged) to do this automatically.

**Comment by WesCossick** [comment]
Although using a pre-commit hook is more automated, it adds significant overhead to every commit. Since in practice only some commits need to be formatted, we've chosen not to use pre-commit hooks for formatting. Further, there are many types of situations where our team might want to commit unformatted code before running the formatter separately.
